### PR TITLE
Add support for nested arrays to simulator frontend and CoreIRSimulator

### PR DESCRIPTION
**Pull request by shacklettbp**

### CODE REVIEW

**Comment by leonardt** [comment]
Can't quite make sense of these changes, but @David-Durst can you confirm that this resolves your issue?

**Comment by leonardt** [comment]
Ah I think I get it now, looks like general support for flattened nested arrays (as per your title!). You need to handle the renaming of the names ("_".join) as well as setting the value.

**Comment by leonardt** [comment]
@David-Durst feel free to merge if you approve, looks good to me

**Comment by David-Durst** [comment]
lgtm

**Pull request merged**
