### PR TITLE
Enabling Ports of Nested Tuples To Be Compiled To CoreIR

### PR DESCRIPTION
**Pull request by David-Durst**
Solves https://github.com/phanrahan/magma/issues/160 and https://github.com/phanrahan/magma/issues/161, but my partition still doesn't work. Will open up another issue for that.

### CODE REVIEW

**Comment by David-Durst** [comment]
0a480d0 fixes another issue, but was attached to this pull request because its on the same branch.

**Comment by leonardt** [comment]
FYI coreir-dev is broken, see https://github.com/rdaly525/coreir/issues/515 to track the issue

**Comment by David-Durst** [comment]
Yep, but I'm still trying to fix the below issue with . I think it should work now that I've added support for nested Tuple types to add_output_port and connect @leonardt have any ideas?

```
    def test_map_4pxPerClock_2PpxParallel():
>       run_test_map_npxPerClock_mparallelism(4,0.5)

tests/test_map.py:82:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_map.py:61: in run_test_map_npxPerClock_mparallelism
    namespaces=["aetherlinglib", "commonlib", "mantle", "coreir", "global"])
../magma/magma/simulator/coreir_simulator.py:129: in __init__
    coreir_.compile(circuit, coreir_filename, context=self.ctx)
../magma/magma/backend/coreir_.py:323: in compile
    modules = CoreIRBackend(context).compile(main)
../magma/magma/backend/coreir_.py:319: in compile
    modules[key.name] = self.compile_definition(key)
../magma/magma/backend/coreir_.py:210: in compile_definition
    self.compile_definition_to_module_definition(definition, module_definition)
../magma/magma/backend/coreir_.py:182: in compile_definition_to_module_definition
    coreir_instance = self.compile_instance(instance, module_definition)
../magma/magma/backend/coreir_.py:141: in compile_instance
    module = lib.modules[name]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <coreir.util.LazyDict object at 0x105585400>, key = 'Counter1Mod2'

    def __getitem__(self, key):
        if not key in self:
>           raise KeyError("Could not find key: {}".format(key))
E           KeyError: 'Could not find key: Counter1Mod2'

../pycoreir/coreir/util.py:25: KeyError
```

**Comment by David-Durst** [comment]
The issue appears to be that cache_definition isn't working. I'm getting two instances of the mapPartiallyParallel circuit definition, and one isn't tracking its dependencies. Thus, it gets compiled before the Counter1Mod2 that it needs.

**Comment by leonardt** [comment]
Can you find out the arguments to `DefineMapPartiallyParallel` for each time that it returns a new definition?  It could be that by using `cirb: CoreIRBackend` and `op: Circuit` cacheing may be behaving differently than expected. Particularly, are you passing the same objects for `cirb` and `op`? Since I believe `lru_cache` will just cache based off the default `__hash__` function which I believe is based off the object id.

**Comment by David-Durst** [comment]
@leonardt This passes now. Good to go?

**Pull request merged**
