### PR TITLE
New generator proposal

### PR DESCRIPTION
**Pull request by rsetaluri**
Proposing new (non-staged) generator syntax. Most notable is the type relationships (Generator -> Circuit -> Instance), and the ease of writing generators (free form in __init__). There are some TODO's but would be great to get feedback.

TODO:
-- Caching
-- Make dataclass-like with parameters

### CODE REVIEW

**Comment by cdonovick** [comment]
This look like an empty PR.  Am I missing something?

**Comment by leonardt** [comment]
I think the branches are backwards (it's proposing master into new-generator)

**Comment by leonardt** [comment]
https://github.com/phanrahan/magma/pull/628

**Comment by rsetaluri** [comment]
@cdonovick yeah my bad, this is a dead PR

**Pull request merged**
